# Environment
env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,24
env = GTK_THEME,catppuccin-mocha-mauve-standard+default
env = MOZ_USE_XINPUT2,1

# Autostart
exec-once = bash -c "sleep 1 && fusuma -d"
exec-once = swww img /home/nithin/Pictures/nordic/wallpapers/earth-in-space.png

# Decoration
decoration {
    rounding = 15
    active_opacity = 0.95
    inactive_opacity = 0.85
    shadow {
        enabled = true
        range = 30
        render_power = 4
        color = rgba(0,0,0,0.6)
    }
    blur {
        enabled = true
        size = 8
        passes = 3
    }
}

# General
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 3
    col.active_border = rgba(ff0000ff) rgba(ff7700ff) rgba(ffff00ff) rgba(00ff00ff) rgba(0000ffff) rgba(8b00ffff) 45deg
    col.inactive_border = rgba(7aa2f7aa) rgba(bb9af7aa) rgba(2ac3deaa) rgba(9d7cd8aa) rgba(f7768eaa) rgba(9ece6aaa) 45deg
}

# Misc
misc {
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
}

# Keybinds
bind = SUPER, D, togglespecialworkspace, magic
bind = SUPER, M, movetoworkspacesilent, special:magic






bind = , F4, exec, aura-cycle.sh
exec-once = sleep 5 && openrgb --device 0 --mode "Rainbow Wave"
