background {
    monitor =
    blur_passes = 0
    blur_size = 0
    path = /home/nithin/Pictures/Wallpapers/blackarch.png
    brightness = 1.0
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%H:%M")"
    color = rgba(ff0000ff)
    font_size = 180
    font_family = Orbitron Bold
    position = 0, -60
    halign = left
    valign = top
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B %Y")"
    color = rgba(ff0000aa)
    font_size = 42
    font_family = Orbitron
    position = 150, -260
    halign = left
    valign = top
}

input-field {
    monitor =
    size = 500, 80
    outline_thickness = 4
    dots_size = 0.3
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgba(ff0000ff)
    inner_color = rgba(00000099)
    font_color = rgba(ff0000ff)
    fade_on_empty = false
    placeholder_text = Enter Password
    hide_input = false
    position = -80, 150
    halign = right
    valign = bottom
    rounding = 16
}

general {
    grace = 0
    no_fade_in = true
    no_fade_out = true
    ignore_empty_input = false
    disable_loading_bar = true
}
