# Reset to neutral theme
background #0a0a0a
foreground #cdd6f4

# Normal colors (Catppuccin-like clean)
color0  #1e1e2e
color1  #ff0000
color2  #a6e3a1
color3  #f9e2af
color4  #89b4fa
color5  #cba6f7
color6  #94e2d5
color7  #bac2de

color8  #585b70
color9  #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #cba6f7
color14 #94e2d5
color15 #a6adc8

background_opacity 0.5
selection_background #30363d
selection_foreground #c9d1d9


# 🔥 FORCE NORMAL SIZE
remember_window_size no

# BIG window defaults
initial_window_width 1600
initial_window_height 900

# make it feel bigger inside
window_padding_width 12

# optional smoother look
confirm_os_window_close 0
