
$GTK_THEME = Vanta-Black
$ICON_THEME = Tela-circle-black
$COLOR_SCHEME=prefer-dark
$CURSOR_THEME = Bibata-Modern-Ice
$CURSOR_SIZE=20
$CODE_THEME=Pure Black

exec = gsettings set org.gnome.desktop.interface icon-theme '$ICON_THEME'
exec = gsettings set org.gnome.desktop.interface gtk-theme '$GTK_THEME'
exec = gsettings set org.gnome.desktop.interface color-scheme '$COLOR_SCHEME'
exec = Hyde cursor theme '$CURSOR_THEME' size $CURSOR_SIZE
exec = Hyde code theme '$CODE_THEME'

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 3
    col.active_border = rgba(ffffffee) rgba(bfbfbfb0) rgba(bfbfbfb0) rgba(ffffffee) 45deg
    col.inactive_border = rgba(2a2a2ab0) rgba(3c3c3cb0) rgba(3c3c3cb0) rgba(2a2a2ab0) 45deg
    resize_on_border = yes
}

decoration {
    rounding = 0

    active_opacity = 0.95
    inactive_opacity = 0.95

    blur {
        enabled = yes
        size = 5
        passes = 4
        ignore_opacity = true
        new_optimizations = true
        xray = false
    }
}

blurls = waybar
